## You can use this file, or make multiple files, to create a conda environment for this project:
##   conda env create -f environment.yml
name: EMN001_Paleofuran
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::snakemake=7.8.0
  - conda-forge::xlsxwriter=0.9.8
  - conda-forge::ffq=0.2.1
  - conda-forge::wget=1.20.3
  - conda-forge::scikit-allel=1.3.5
